In [1]:
import cv2
import pandas as pd 
import numpy as np
import face_recognition
from datetime import datetime

In [2]:
import os

In [3]:
path='Imageauth/'
Image=[]
classNames=[]
myList=os.listdir(path)
print(myList)

['billgate.jpg', 'elon_musk1.jpg', 'Jack ma.jpg', 'Mukhtar.jpg']


In [4]:
for cl in myList:
    curImg=cv2.imread(f'{path}/{cl}')
    Image.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['billgate', 'elon_musk1', 'Jack ma', 'Mukhtar']


In [ ]:
#find Encoding

def findEncoding(Image):
    encodelist=[]
    for img in Image:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encode=face_recognition.face_encodings(img)[0]
        encodelist.append(encode)
    return encodelist

encodelistKnown=findEncoding(Image)
print("Encoding Complete")

Encoding Complete


In [ ]:
def markAttendance(name):
    with open('Attendance.csv','r+')as f:
        mydatalist=f.readlines()
        nameslist=[]
        #print(mydatalist)
        for line in mydatalist:
            entry=line.split(',')
            nameslist.append(entry[0])
        if name not in nameslist:
            now=datetime.now()
            dtstring=now.strftime('%H:%M:%S')
            f.writelines(f'\n{name}.{dtstring}')
            
       

In [ ]:
cap=cv2.VideoCapture(0)

while True:
    success,img=cap.read()
    imgS=cv2.resize(img,(0,0),None,0.25,0.25)# resize image cuz we want small img to process
    imgS=cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB) # conveting img color
    faceCurLoc=face_recognition.face_locations(imgS) #caputre multi faces
    encodeCurframe= face_recognition.face_encodings(imgS,faceCurLoc) # encode the milti faces & find right one
    
    # finding the matches through faces that r found
    for encodeFace,faceLoc in zip(encodeCurframe,faceCurLoc):
        matchs=face_recognition.compare_faces(encodelistKnown,encodeFace)
        facedis=face_recognition.face_distance(encodelistKnown,encodeFace)
        print(facedis)
        matchIndex=np.argmin(facedis) # it give min. values index the lower the values more acurate match
        
        if matchs[matchIndex]:
            name=classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1=faceLoc
            y1,x2,y2,x2=y1*4,x2*4,y2*4,x2*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name) 
    
    cv2.imshow('webcam',img)
    cv2.waitKey(1)
    
    
    

[0.91742286 0.83364632 0.82751803 0.36076057]
MUKHTAR
[0.92793631 0.8617123  0.79336703 0.38678995]
MUKHTAR
[0.94682647 0.87380244 0.823163   0.44538803]
MUKHTAR
[0.93164064 0.89967771 0.82567507 0.43709267]
MUKHTAR
[0.94311477 0.87968036 0.82596089 0.4685847 ]
MUKHTAR
[0.93398204 0.86642868 0.80945503 0.40460036]
MUKHTAR
[0.92887529 0.86983882 0.78136913 0.40357891]
MUKHTAR
[0.92834996 0.86272616 0.80633779 0.41746185]
MUKHTAR
[0.88027693 0.83857246 0.8221497  0.39367193]
MUKHTAR
[0.88604441 0.82571502 0.77925655 0.43334653]
MUKHTAR
[0.9222215  0.80956335 0.79254257 0.40045631]
MUKHTAR
[0.93361611 0.83719586 0.82628378 0.38324427]
MUKHTAR
[0.8973839  0.80912272 0.79349439 0.37211562]
MUKHTAR
[0.87902643 0.83448927 0.80924832 0.4133455 ]
MUKHTAR
[0.88711604 0.83511645 0.81202046 0.40972808]
MUKHTAR
[0.91026663 0.84591119 0.842032   0.4018243 ]
MUKHTAR
[0.94030067 0.89883924 0.82815526 0.46657781]
MUKHTAR
[0.92737137 0.85787815 0.85105    0.41790637]
MUKHTAR
[0.91566878 0.85186266 0.841